In [1]:
import array as a
a.array


array.array

In [8]:
import array as a
student_roll = a.array('i',[1,3,5,8,6,2])
print(student_roll)
print(student_roll[5])

array('i', [1, 3, 5, 8, 6, 2])
2


In [10]:
from array import *
A = array('i',[1,5,6,9,9,7,95,57,42,69,5,1,5])
B = array('i',[10,20,30])
print(A)
A.append(23)
print(A)
A.remove(7)
print(A)
A.insert(1,90)
print(A)
A.extend(B)
print(A)
C = [99,89,79]
A.fromlist(C)
print(A)
A.pop()
print(A)
A[5]
A.index(5)
A.reverse()
print(A)

A.buffer_info()
A.count(5)

H = A.tolist()
print(H)



array('i', [1, 5, 6, 9, 9, 7, 95, 57, 42, 69, 5, 1, 5])
array('i', [1, 5, 6, 9, 9, 7, 95, 57, 42, 69, 5, 1, 5, 23])
array('i', [1, 5, 6, 9, 9, 95, 57, 42, 69, 5, 1, 5, 23])
array('i', [1, 90, 5, 6, 9, 9, 95, 57, 42, 69, 5, 1, 5, 23])
array('i', [1, 90, 5, 6, 9, 9, 95, 57, 42, 69, 5, 1, 5, 23, 10, 20, 30])
array('i', [1, 90, 5, 6, 9, 9, 95, 57, 42, 69, 5, 1, 5, 23, 10, 20, 30, 99, 89, 79])
array('i', [1, 90, 5, 6, 9, 9, 95, 57, 42, 69, 5, 1, 5, 23, 10, 20, 30, 99, 89])
array('i', [89, 99, 30, 20, 10, 23, 5, 1, 5, 69, 42, 57, 95, 9, 9, 6, 5, 90, 1])
[89, 99, 30, 20, 10, 23, 5, 1, 5, 69, 42, 57, 95, 9, 9, 6, 5, 90, 1]


In [8]:
from array import *
A = array('str', ['r','a'])
print(A.tostring())


TypeError: array() argument 1 must be a unicode character, not str

In [5]:
lst=[[1,2,3],[4,5,6],[7,8,9]]
print(lst[0][0])
print(lst[1])

1
[4, 5, 6]


In [18]:
lft = [[[111,112,113],[121,122,123],[131,132,133]],[[211,212,213],[221,222,223],[231,232,233]],[[311,312,
313],[321,322,323],[331,332,333]]]
print(lft[1][1])

[221, 222, 223]


In [6]:
from array import *
x = array('i',[[1,2,3],[4,5,6],[7,8,9]])

print(x)




y = array('i',[[[111,112,113],[121,122,123],[131,132,133]],[[211,212,213],[221,222,223],[231,232,233]],[[311,312,
313],[321,322,323],[331,332,333]]])

print(y)

z=array('i',[1,2,3,4,5,6,7])
print(z)

TypeError: an integer is required (got type list)

In [9]:
d = array('i',[[1,2],[3,4]])
print(d)

TypeError: an integer is required (got type list)

In [1]:
from numpy import *


r = array([2,3,4,5,6])
print(r)

print(r[0])

# change the value of element
r[3]= 99
print(r)

# find the type of elements
print(r.dtype)

# change the data type of elements
s = array([2,3,4,5,6], dtype=float)
print(s)

print(s.dtype)

n = len(s)
for i in range(n):
    print(i,"=",s[i])
   
for b in s:
    print(b)
    
    
b.pop()
print(b)

[2 3 4 5 6]
2
[ 2  3  4 99  6]
int32
[2. 3. 4. 5. 6.]
float64
0 = 2.0
1 = 3.0
2 = 4.0
3 = 5.0
4 = 6.0
2.0
3.0
4.0
5.0
6.0


AttributeError: 'numpy.float64' object has no attribute 'pop'

In [1]:
from array import *
blank = array('i',[])
n = int(input('enter the len of array '))

for i in range(n):
    x = int(input('enter the next value '))
    blank.append(x)
print(blank) 
    


enter the len of array 5
enter the next value 12
enter the next value 13
enter the next value 14
enter the next value 15
enter the next value 16
array('i', [12, 13, 14, 15, 16])


In [2]:
from array import *
k = array('i',[12,13,14,15,16])

k.pop()
print(k)

array('i', [12, 13, 14, 15])


In [ ]:
from array import *
stu_name = array('d',[])
n = int(input('enter the of elements'))
for i in range(n):
    name = input('enter your name')
    stu_name.append(name)
print(stu_name)
    

In [11]:
from array import *
A = array('i',[1,5,6,9,9,7,95,57,42,69,5,1,5])
B = array('i',[10,20,30])
C = [99,89,79]
A.fromlist(C)
print(A)
A.extend(B)
print(A)
A.pop()
print(A)
A[5]
A.index(5)
A.reverse()
print(A)

A.buffer_info()

A.count(5)
v = A.tolist()
print(v)

array('i', [1, 5, 6, 9, 9, 7, 95, 57, 42, 69, 5, 1, 5, 99, 89, 79])
array('i', [1, 5, 6, 9, 9, 7, 95, 57, 42, 69, 5, 1, 5, 99, 89, 79, 10, 20, 30])
array('i', [1, 5, 6, 9, 9, 7, 95, 57, 42, 69, 5, 1, 5, 99, 89, 79, 10, 20])
array('i', [20, 10, 79, 89, 99, 5, 1, 5, 69, 42, 57, 95, 7, 9, 9, 6, 5, 1])
[20, 10, 79, 89, 99, 5, 1, 5, 69, 42, 57, 95, 7, 9, 9, 6, 5, 1]


In [2]:
from numpy import*
a = linspace(1,8,8)
for i in a:
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0


In [16]:
import numpy as np

b = np.array([101,102,103])
print(b)
print(type(b))


print(np.__version__)

[101 102 103]
<class 'numpy.ndarray'>
1.20.1


In [22]:
import numpy as np
A = np.array(12)
print(A)


B = np.array([[1,2,3],[4,5,6]])
print(B)

C = np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
print(C)


print(A.ndim)
print(B.ndim)
print(C.ndim)


print(B[1][0])

print(C[1,1,2]) 

12
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
0
2
3
4
11


In [15]:
import numpy as np

a = np.array([1,2,3,4])
print(a)
print(a[0])
print(a[2]+a[3])

[1 2 3 4]
1
7


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [2]:
import numpy as np
A = np.array([101,102,103,104,105,106,107,108,109])
print(A[:2])
print(A[:-1])
print(A[1:6:2])


B = np.array([[101,102,103,104],[105,106,107,108]])
print(B[0])
print(B[1])


[101 102]
[101 102 103 104 105 106 107 108]
[102 104 106]
[101 102 103 104]
[105 106 107 108]


In [13]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2,1:1])

[]


In [25]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

print(arr[0:5, 0:3])

print(arr.ndim)
print(arr.dtype)
print(arr.type())

arr3 = np.array([[[1,2,3],]])

[3 8]
[[1 2 3]
 [6 7 8]]
2
int32


AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [31]:
import numpy as np

arr = np.array(['apple','mango','banana','pineapple','cherry','dragon fruit'])

print(arr.dtype)

<U12


In [32]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1, 4.1])

print(arr.dtype)


float64


In [37]:
import numpy as np

arr = np.array([])

print(arr.dtype)

float64


In [7]:
import numpy as np
arr3 = np.array([[[1,2,3],[4,0,6]],[[7,8,9],[10,11,12]]])
print(arr3[0:,1,0:2])
print(type(arr3))
print(arr3.dtype) 
np.zeros(0)

[[ 4  0]
 [10 11]]
<class 'numpy.ndarray'>
int32


array([], dtype=float64)

In [11]:
np.zeros([0,3])


array([], shape=(0, 3), dtype=float64)

In [9]:
np.zeros((0,1))

array([], shape=(0, 1), dtype=float64)

In [18]:
arr = np.array([1, 2, 3, 4], dtype='')

print(arr)
print(arr.dtype)

[1 2 3 4]
int8


In [6]:
import numpy as np
A = np.array([1,2,3,4,5,6])

b = A.copy()
c = A.view()
c[1] = 13
A[0] = 12

print(A)
print(b)
print(c)
print(b.base)
print(c.base)


[12 13  3  4  5  6]
[1 2 3 4 5 6]
[12 13  3  4  5  6]
None
[12 13  3  4  5  6]


In [9]:
B = np.array([[1,2,3,10],[4,5,6,7]])
print(B.shape)

(2, 4)


In [11]:
C = np.array([1,2,3,4],ndmin = 5)
print(C.shape)

(1, 1, 1, 1, 4)


In [12]:
D = np.array([1,2,3,4],ndmin = 3)
print(D.shape)

(1, 1, 4)


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
a = np.array([11,12,13,14,15,16,17,18,19,20])
b = a.reshape(2,5)
print(b)

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [9]:
a = np.array([11,12,13,14,15,16,17,18,19,20,21,22])
c = a.reshape(2)
print(c) 

ValueError: cannot reshape array of size 12 into shape (2,3,1)

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(A.ndim)

for i in A:
    
    for j in i:
        print(j)




2
1
2
3
4
5
6
7
8
9
10
11
12


In [4]:
B = np.array([1,2,3,4,5,6])
for i in B:
    print(i)

1
2
3
4
5
6


In [14]:
c = np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
for x in c:
    for y in x:
        for z in y:
            print(z)
            
        
for i in np.nditer(c):
    print(i)
    

1
2
3
3
4
5
6
7
8
9
10
11
1
2
3
3
4
5
6
7
8
9
10
11


In [21]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['U']):
    print(x)

TypeError: Iterator operand 0 dtype could not be cast from dtype('int32') to dtype('float32') according to the rule 'safe'

In [22]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [27]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

c = np.stack((a,b), axis = 1)
d = np.hstack((a,b))
e = np.vstack((a,b))
f = np.dstack((a,b))
print(c)
print(d)
print(e)
print(f)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [5]:
import numpy as np
A = np.array([1,2,3,4,5,6])
B = np.array_split(A,5)
print(B)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [8]:
A2 = np.array([[1,2,3],[4,5,6]])
B2 = np.array_split(A2,3)
B3 = np.array_split(A2,2)
print(B2)
print(B3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [9]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b2 = np.array_split(a2,3)
b3 = np.array_split(a2,2)
print(b2)
print(b3)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [10]:
ar2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
arr2 = np.array_split(ar2,3,axis = 1)
print(arr2)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr%2==0)

print(x)

(array([1, 3, 5, 6], dtype=int64),)


In [14]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

c =np.concatenate((a,b))
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
import os
print("file name  :    ", os.getcwd() )
print("current file name      :    ", os.path.dirname() )

file name  :     D:\jupyter


NameError: name 'file' is not defined